#!/usr/bin/env python3
"""Generate the FinQA numerical supplement tables.

Table A (estimation), one row per generator x workflow x metric x budget:
absolute uniform panel MSE, anchor/uniform, anchor/occupancy and
anchor/rollout ratios, and the paired z for uniform minus anchor.
Table B (decision), one row per generator x metric x budget: exact panel
values for both templates, their signed gap, and wrong-selection rates
for every practical method plus the oracle reference.

Reads results/finqa_paper_numbers.json (frozen metric) and
results/finqa_paper_numbers_ua.json (semantic unit-aware variant).
Writes build/finqa_supplement_tables.tex.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = {"frozen": "finqa_paper_numbers.json", "unit-aware": "finqa_paper_numbers_ua.json"}
BUDGETS = ("25", "50", "100", "200")


def sci(x: float) -> str:
    m, e = f"{x:.1e}".split("e")
    return f"${m}\\,e{{{int(e)}}}$"


def main() -> None:
    reports = {m: json.loads((ROOT / "results" / f).read_text()) for m, f in SOURCES.items()}
    a_rows, b_rows = [], []
    for metric, rep in reports.items():
        for gen in ("qwen", "phi"):
            for wf in ("ordinary", "unitcheck"):
                for b in BUDGETS:
                    cell = rep["panel"][f"{gen}|{wf}"].get(b)
                    if not cell:
                        continue
                    u = cell["uniform"]["panel_mse"]
                    anc = cell["tis_anchored"]["normalized_to_uniform"]
                    occ = cell["learned_occupancy"]["normalized_to_uniform"]
                    rol = cell["complete_rollout"]["normalized_to_uniform"]
                    z = rep["paired"][f"{gen}|{wf}"].get(
                        f"uniform-tis_anchored|b{b}", {}).get("z", float("nan"))
                    a_rows.append(
                        f"{gen} & {wf.replace('unitcheck','unit check')} & {metric} & {b} & "
                        f"{sci(u)} & {anc:.3f} & {anc/occ:.2f} & {anc/rol:.2f} & "
                        f"{z:+.1f}\\\\")
            dec = rep["workflow_decision"].get(gen)
            if not dec:
                continue
            vals = dec["population_values"]
            for b in (25, 50, 100, 200):
                row = {r["method"]: r for r in dec["rows"] if r["budget"] == b}
                if not row:
                    continue
                wr = lambda m: f"{100*row[m]['wrong_rate']:.1f}" if m in row and "wrong_rate" in row[m] else "--"
                b_rows.append(
                    f"{gen} & {metric} & {b} & {vals['ordinary']:.5f} & "
                    f"{vals['unitcheck']:.5f} & {dec['population_gap']:+.5f} & "
                    f"{wr('uniform')} & {wr('tis')} & {wr('learned_occupancy')} & "
                    f"{wr('complete_rollout')} & {wr('tis_anchored')} & {wr('oracle_tail')}\\\\")

    out = ROOT / "build" / "finqa_supplement_tables.tex"
    out.parent.mkdir(exist_ok=True)
    out.write_text(
        "% Generated by scripts/finqa_supplement_tables.py -- do not edit.\n"
        "% Table A rows:\n" + "\n".join(a_rows) +
        "\n% Table B rows:\n" + "\n".join(b_rows) + "\n")
    print(out, f"({len(a_rows)} estimation rows, {len(b_rows)} decision rows)")


if __name__ == "__main__":
    main()
