#!/usr/bin/env python3
"""Computational and query-cost accounting for the language-model study.

Collects, per generator: GPU calibration cost (wall time, forward calls,
prompt tokens) from the frozen kernel artifacts; direct-generation audit
cost from the frozen audit reports; CPU simulation cost (wall time, worker
processes) from every available result manifest (original grid, closed
grid, extension, floor runs); and the structural constants of the design
(groups, questions, grid atoms per horizon for both grids, pilot draws
and pilot fractions per budget). Writes
``results/llm_compute_costs.json`` and a supplement table body to
``build/llm_cost_table.tex``.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from tis.allocation import pilot_size  # noqa: E402
from tis.llm_study.protocol import exact_return_grid  # noqa: E402

GENERATORS = [
    ("Qwen3-4B", "", "qwen_kernels.json", "generation_audit.json"),
    ("Phi-4-mini", "_robustness", "robustness_kernels.json", "generation_audit_robustness.json"),
    ("Granite-4.2-8B", "_robustness2", "robustness2_kernels.json", "generation_audit_robustness2.json"),
    ("Mistral-24B", "_scale1", "scale1_kernels.json", "generation_audit_scale1.json"),
    ("Qwen3-32B", "_scale2", "scale2_kernels.json", "generation_audit_scale2.json"),
    ("GLM-4-32B", "_scale3", "scale3_kernels.json", "generation_audit_scale3.json"),
]
LABELS = {
    "Qwen3-4B": "Qwen3-4B (primary)", "Phi-4-mini": "Phi-4-mini",
    "Granite-4.2-8B": "Granite-4.2-8B", "Mistral-24B": "Mistral-24B$^\\dagger$",
    "Qwen3-32B": "Qwen3-32B$^\\dagger$", "GLM-4-32B": "GLM-4-32B$^\\dagger$",
}
RESULT_FAMILIES = {
    "panel_original": "results/llm_study_paper{s}",
    "panel_closed": "results/llm_study_closed{s}",
    "extension_closed": "results/llm_study_ext_closed{s}",
}
GROUPS = 91
BUDGETS = (50, 100, 200, 400)


def manifest_cost(directory: Path) -> dict | None:
    path = directory / "manifest.json"
    if not path.exists():
        return None
    manifest = json.loads(path.read_text())
    return {
        "runtime_seconds": manifest.get("runtime_seconds"),
        "worker_processes": manifest.get("worker_processes"),
        "cells_from_cache": manifest.get("cells_from_cache"),
        "status": manifest.get("result_evidence_status"),
    }


def main() -> None:
    grids = {}
    for horizon in (2, 4, 6):
        study = exact_return_grid(horizon)
        closed = exact_return_grid(horizon, closed=True)
        grids[str(horizon)] = {
            "atoms_original": len(study),
            "atoms_closed": len(closed),
            "min_gap_original": float(min(study[1:] - study[:-1])),
            "min_gap_closed": float(min(closed[1:] - closed[:-1])),
        }
    pilots = {}
    for budget in BUDGETS:
        total = GROUPS * budget
        per_group = pilot_size(total, GROUPS, 4.0, 8, 2)
        pilots[str(budget)] = {
            "pilot_per_group": per_group,
            "pilot_fraction": per_group * GROUPS / total,
        }

    report: dict[str, object] = {
        "design": {
            "questions": 50,
            "shared_groups_per_question": GROUPS,
            "replications": 300,
            "grid": grids,
            "pilot_schedule": pilots,
        },
        "generators": {},
    }
    for label, suffix, kernel_file, audit_file in GENERATORS:
        artifact = json.loads((ROOT / "frozen" / kernel_file).read_text())
        audit = json.loads((ROOT / "frozen" / audit_file).read_text())
        entry: dict[str, object] = {
            "calibration": artifact.get("calibration_cost"),
            "audit": {
                "wall_seconds": audit.get("wall_seconds"),
                "audited_cells": audit.get("audited_cells"),
                "samples_per_prompt": audit.get("samples_per_prompt"),
            },
            "simulation": {},
        }
        for family, pattern in RESULT_FAMILIES.items():
            cost = manifest_cost(ROOT / pattern.format(s=suffix))
            if cost is not None:
                entry["simulation"][family] = cost
        report["generators"][label] = entry

    out = ROOT / "results" / "llm_compute_costs.json"
    out.write_text(json.dumps(report, indent=1, sort_keys=True) + "\n")

    lines = [
        "% Generated by scripts/llm_cost_report.py -- do not edit by hand.",
        "% Columns: calibration GPU minutes / forward calls; audit GPU minutes;",
        "% panel simulation CPU core-hours (closed grid where available).",
    ]
    for label, suffix, *_ in GENERATORS:
        entry = report["generators"][label]
        cal = entry["calibration"] or {}
        sim = entry["simulation"].get("panel_closed") or entry["simulation"].get("panel_original") or {}
        core_hours = (
            sim.get("runtime_seconds", 0.0) * sim.get("worker_processes", 0) / 3600.0
            if sim
            else None
        )
        lines.append(
            f"{LABELS[label]} & "
            f"{(cal.get('wall_seconds') or 0) / 60:.0f} & "
            f"{cal.get('model_forward_calls', '--')} & "
            f"{(entry['audit'].get('wall_seconds') or 0) / 60:.0f} & "
            + (f"{core_hours:.0f}" if core_hours else "--")
            + r"\\"
        )
    build = ROOT / "build"
    build.mkdir(exist_ok=True)
    (build / "llm_cost_table.tex").write_text("\n".join(lines) + "\n")
    print(out)
    for label in report["generators"]:
        entry = report["generators"][label]
        cal = entry["calibration"] or {}
        print(
            "%-15s calib %5.0fs audit %5.0fs sims: %s"
            % (
                label,
                cal.get("wall_seconds") or -1,
                entry["audit"].get("wall_seconds") or -1,
                {k: round(v["runtime_seconds"]) for k, v in entry["simulation"].items()},
            )
        )


if __name__ == "__main__":
    main()
