#!/usr/bin/env python3
"""Summarize the fair-baseline extension of the language-model study.

Reads the extension result directories (``results/llm_study_ext_closed*``
by default; ``--original`` switches to ``results/llm_study_ext*``) and the
matching main-panel directories, then writes
``results/llm_extension_numbers.json`` and a supplement table body to
``build/llm_extension_table.tex``.

The extension panel adds, over the same frozen kernels, seeds, grouping,
and pilot draws as the prespecified study:

- ``learned_mean`` / ``learned_occupancy``: pilot-estimated mean-influence
  and occupancy scores with the same charged pilot as TIS;
- ``tis_no_cov``: the TIS pilot with cross-layer covariance deleted from
  the allocation score only (identical pooling and pilot);
- ``oracle_no_cov``: the population counterpart.

The anchors (uniform, oracle_tail, tis) must reproduce the main panel's
coupled-stream errors exactly; the script asserts this cell by cell.
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORIGINAL = "--original" in sys.argv[1:]
EXT = "llm_study_ext" if ORIGINAL else "llm_study_ext_closed"
MAIN = "llm_study_paper" if ORIGINAL else "llm_study_closed"
GENERATORS = [
    ("Qwen3-4B", ""),
    ("Phi-4-mini", "_robustness"),
    ("Granite-4.2-8B", "_robustness2"),
    ("Mistral-24B", "_scale1"),
    ("Qwen3-32B", "_scale2"),
    ("GLM-4-32B", "_scale3"),
]
LABELS = {
    "Qwen3-4B": "Qwen3-4B (primary)", "Phi-4-mini": "Phi-4-mini",
    "Granite-4.2-8B": "Granite-4.2-8B", "Mistral-24B": "Mistral-24B$^\\dagger$",
    "Qwen3-32B": "Qwen3-32B$^\\dagger$", "GLM-4-32B": "GLM-4-32B$^\\dagger$",
}
EXT_METHODS = ("learned_mean", "learned_occupancy", "tis_no_cov", "oracle_no_cov")
HORIZONS = ("2", "4", "6")


def f3(x: float) -> str:
    return ("%.3f" % x).lstrip("0") if x < 1 else "%.2f" % x


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as stream:
        return list(csv.DictReader(stream))


def main() -> None:
    numbers: dict[str, dict] = {}
    for label, suffix in GENERATORS:
        base = ROOT / "results" / f"{EXT}{suffix}"
        if not (base / "manifest.json").exists():
            continue
        summary = {}
        for r in read_rows(base / "panel_summary.csv"):
            summary[(r["horizon"], r["alpha"], r["budget_per_shared_group"], r["method"])] = (
                float(r["panel_mse"]),
                float(r["normalized_to_uniform"]) if r["normalized_to_uniform"] else None,
            )
        paired = {}
        for r in read_rows(base / "paired_panel.csv"):
            key = (r["horizon"], r["alpha"], r["budget_per_shared_group"], r["comparison"])
            paired[key] = float(r["mean_difference"]) / float(r["se"]) if float(r["se"]) > 0 else 0.0

        main_dir = ROOT / "results" / f"{MAIN}{suffix}"
        anchors_match = None
        if (main_dir / "panel_summary.csv").exists():
            main_summary = {
                (r["horizon"], r["alpha"], r["budget_per_shared_group"], r["method"]): float(r["panel_mse"])
                for r in read_rows(main_dir / "panel_summary.csv")
            }
            anchors_match = True
            for key, (mse, _) in summary.items():
                if key[3] in ("uniform", "oracle_tail", "tis") and key in main_summary:
                    if abs(mse - main_summary[key]) > 1e-12 * max(abs(mse), 1e-300):
                        anchors_match = False
        entry = {
            "status": json.loads((base / "manifest.json").read_text())["result_evidence_status"],
            "anchors_match_main_panel": anchors_match,
            "norm400": {
                f"{h}|{a}|{m}": summary[(h, a, "400", m)][1]
                for h in HORIZONS
                for a in ("0.1", "0.2")
                for m in ("tis", "oracle_tail") + EXT_METHODS
            },
            "z_vs_tis_400_a01": {
                f"{h}|{m}": paired.get((h, "0.1", "400", f"{m}-minus-tis"))
                for h in HORIZONS
                for m in EXT_METHODS
            },
        }
        numbers[label] = entry

    out = ROOT / "results" / "llm_extension_numbers.json"
    out.write_text(json.dumps(numbers, indent=1, sort_keys=True) + "\n")
    build = ROOT / "build"
    build.mkdir(exist_ok=True)
    lines = [
        "% Generated by scripts/llm_extension_analysis.py -- do not edit by hand.",
        "% Rows: generator x horizon; columns: TIS, learned mean, learned occupancy,",
        "% TIS w/o covariance, oracle w/o covariance, oracle tail (all /uniform, alpha=.1, b=400).",
    ]
    for label, _ in GENERATORS:
        if label not in numbers:
            continue
        v = numbers[label]["norm400"]
        for h in HORIZONS:
            head = LABELS[label] if h == "2" else ""
            cells = [
                f3(v[f"{h}|0.1|{m}"])
                for m in ("tis", "learned_mean", "learned_occupancy", "tis_no_cov", "oracle_no_cov", "oracle_tail")
            ]
            lines.append(f"{head} & $H={h}$ & " + " & ".join(cells) + r"\\")
        lines.append(r"\midrule")
    (build / "llm_extension_table.tex").write_text("\n".join(lines[:-1]) + "\n")

    for label in numbers:
        v = numbers[label]
        print(
            "%-15s %s anchors_ok=%s | H6 a.1: tis %s lm %s lo %s nocov %s"
            % (
                label,
                v["status"],
                v["anchors_match_main_panel"],
                f3(v["norm400"]["6|0.1|tis"]),
                f3(v["norm400"]["6|0.1|learned_mean"]),
                f3(v["norm400"]["6|0.1|learned_occupancy"]),
                f3(v["norm400"]["6|0.1|tis_no_cov"]),
            )
        )
    print("wrote", out, "and", build / "llm_extension_table.tex")


if __name__ == "__main__":
    main()
