#!/usr/bin/env python3
"""Anchored TIS versus the strongest baselines, with paired uncertainty.

For every generator at H = 6, alpha = .1, 400 queries per kernel, computes
the panel-mean MSE ratio of anchored TIS to plain TIS, learned occupancy,
and complete rollouts, together with the paired mean difference of
per-replication panel MSEs and its 95% normal interval. Anchored TIS,
plain TIS, and learned occupancy are paired within the anchored run;
the rollout estimator lives in its own run but shares the master seed,
question panel, and pilot streams, so pairing replication indices across
runs remains a valid variance-reduced design (the anchor methods reproduce
across runs exactly). Population-informed methods are excluded.

Reads the committed panel_replications.csv files; writes
results/llm_strongest_baseline.json and build/llm_strongest_baseline.tex.
"""
from __future__ import annotations

import csv
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GENS = [
    ("Qwen3-4B", ""), ("Phi-4-mini", "_robustness"), ("Granite-4.2-8B", "_robustness2"),
    ("Mistral-24B", "_scale1"), ("Qwen3-32B", "_scale2"), ("GLM-4-32B", "_scale3"),
]
LAB = {"Qwen3-4B": "Qwen3-4B (primary)", "Phi-4-mini": "Phi-4-mini",
       "Granite-4.2-8B": "Granite-4.2-8B", "Mistral-24B": "Mistral-24B$^\\dagger$",
       "Qwen3-32B": "Qwen3-32B$^\\dagger$", "GLM-4-32B": "GLM-4-32B$^\\dagger$"}
CELL = ("6", "0.1", "400")


def replication_mses(directory: Path, methods) -> dict[str, dict[int, float]]:
    out: dict[str, dict[int, float]] = {m: {} for m in methods}
    with (directory / "panel_replications.csv").open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if (row["horizon"], row["alpha"], row["budget_per_shared_group"]) != CELL:
                continue
            if row["method"] in out:
                out[row["method"]][int(row["replication"])] = float(
                    row["panel_mean_squared_error"]
                )
    return out


def paired(a: dict[int, float], b: dict[int, float]) -> dict:
    """Mean difference b - a (positive favors a) with 95% normal interval."""
    keys = sorted(set(a) & set(b))
    diffs = [b[k] - a[k] for k in keys]
    n = len(diffs)
    mean = sum(diffs) / n
    var = sum((x - mean) ** 2 for x in diffs) / (n - 1)
    se = math.sqrt(var / n)
    return {
        "n": n,
        "mean_difference": mean,
        "ci95": [mean - 1.96 * se, mean + 1.96 * se],
        "z": mean / se if se > 0 else float("inf"),
        "resolved": (mean - 1.96 * se) > 0 or (mean + 1.96 * se) < 0,
    }


def main() -> None:
    report: dict[str, dict] = {}
    for label, suffix in GENS:
        anch = replication_mses(
            ROOT / "results" / f"llm_study_anchored{suffix}",
            {"tis_anchored", "tis", "learned_occupancy", "uniform"},
        )
        roll = replication_mses(
            ROOT / "results" / f"llm_study_rollout{suffix}", {"complete_rollout"}
        )
        uniform_mean = sum(anch["uniform"].values()) / len(anch["uniform"])
        entry: dict[str, object] = {
            "ratio_to_uniform": {
                m: (sum(v.values()) / len(v)) / uniform_mean
                for m, v in {**anch, "complete_rollout": roll["complete_rollout"]}.items()
                if m != "uniform"
            }
        }
        for name, other in (
            ("vs_tis", anch["tis"]),
            ("vs_learned_occupancy", anch["learned_occupancy"]),
            ("vs_complete_rollout", roll["complete_rollout"]),
        ):
            entry[name] = paired(anch["tis_anchored"], other)
        report[label] = entry

    out = ROOT / "results" / "llm_strongest_baseline.json"
    out.write_text(json.dumps(report, indent=1, sort_keys=True) + "\n")

    def cell(entry, key):
        p = entry[key]
        mark = "$^*$" if p["resolved"] else ""
        return f"{p['mean_difference']:.1e}{mark}"

    lines = [
        "% Generated by scripts/strongest_baseline_table.py -- do not edit by hand.",
        "% Paired mean difference (baseline minus anchored) of per-replication",
        "% panel MSEs at H=6, alpha=.1, b=400; positive favors anchored TIS;",
        "% * marks 95% intervals excluding zero.",
    ]
    for label, _ in GENS:
        e = report[label]
        r = e["ratio_to_uniform"]
        lines.append(
            f"{LAB[label]} & {r['tis_anchored']:.3f} & "
            + " & ".join(cell(e, k) for k in ("vs_tis", "vs_learned_occupancy", "vs_complete_rollout"))
            + r"\\"
        )
    (ROOT / "build").mkdir(exist_ok=True)
    (ROOT / "build" / "llm_strongest_baseline.tex").write_text("\n".join(lines) + "\n")
    print(out)
    for label, _ in GENS:
        e = report[label]
        print(
            f"{label:14s} anchored/unif {e['ratio_to_uniform']['tis_anchored']:.3f} | "
            f"vs occ z={e['vs_learned_occupancy']['z']:+.1f} resolved={e['vs_learned_occupancy']['resolved']} | "
            f"vs rollout z={e['vs_complete_rollout']['z']:+.1f} resolved={e['vs_complete_rollout']['resolved']}"
        )


if __name__ == "__main__":
    main()
